export const ANCHOR_PLACEMENT_HEIGHT = 0.5;
export const ANCHOR_GAUSSIAN_HIGHLIGHT_ENABLED = false;
export const ANCHOR_PLACEMENT_FLASHLIGHT_BOTTOM_OFFSET = 0.1;
export const ANCHOR_PLACEMENT_FLASHLIGHT_COLOR: [number, number, number] = [
  1, 0.98, 0.92,
];
export const ANCHOR_PLACEMENT_FLASHLIGHT_RADIUS = 0.15;
export const ANCHOR_PLACEMENT_FLASHLIGHT_STRENGTH = 1.1;
export const ANCHOR_PLACEMENT_RIPPLE_AMPLITUDE = 0.035;
export const ANCHOR_PLACEMENT_RIPPLE_RADIUS = 0.15;
export const ANCHOR_PLACEMENT_RIPPLE_SPEED = 1.05;
export const ANCHOR_PLACEMENT_RIPPLE_TINT_COLOR: [number, number, number] = [
  1, 0.98, 0.92,
];
export const ANCHOR_PLACEMENT_RIPPLE_TINT_STRENGTH = 0.22;
export const ANCHOR_PLACEMENT_RIPPLE_VERTICAL_CORE_RADIUS = 0.05;
export const ANCHOR_PLACEMENT_RIPPLE_VERTICAL_FALLOFF_RADIUS = 0.2;
export const ANCHOR_PLACEMENT_RIPPLE_WAVELENGTH = 0.035;
