export const ANCHOR_PLACEMENT_HEIGHT = 0.2;
export const ANCHOR_PLACEMENT_HIGHLIGHT_RADIUS = 0.12;
export const ANCHOR_PLACEMENT_HIGHLIGHT_STRENGTH = 0.65;
export const ANCHOR_PLACEMENT_FLOAT_AMPLITUDE = 0.02;
export const ANCHOR_PLACEMENT_FLOAT_FREQUENCY = 1.25;
