export const ANCHOR_PLACEMENT_HEIGHT = 0.5;
export const ANCHOR_PLACEMENT_HIGHLIGHT_BOTTOM_OFFSET = 0.1;
export const ANCHOR_PLACEMENT_HIGHLIGHT_RADIUS = 0.12;
export const ANCHOR_PLACEMENT_HIGHLIGHT_STRENGTH = 0.75;
