from typing import Protocol

from camera_path.models import Project


class ProjectRepository(Protocol):
    """Temporary aggregate persistence port until resources receive separate tables."""

    async def create(self, project: Project) -> Project: ...

    async def get(self, project_id: str) -> Project: ...

    async def list(self) -> list[Project]: ...

    async def commit(self, draft: Project, expected_revision: int) -> Project: ...

    async def delete(self, project_id: str) -> None: ...

    async def close(self) -> None: ...
