"""Local filesystem implementation of the library storage contract."""

import asyncio
from pathlib import Path

from fastapi import Request

from camera_path.services.library_storage import LibraryStorage


class LocalLibraryStorage(LibraryStorage):
    def __init__(self, directory: Path) -> None:
        self.directory = directory.expanduser().resolve()
        self.directory.mkdir(parents=True, exist_ok=True)

    def path(self, key: str) -> Path:
        # Keys are generated by the server, never derived from user filenames.
        if Path(key).name != key or key in {".", ".."}:
            raise ValueError("invalid library key")
        return self.directory / key

    async def upload_url(self, asset_id: str, key: str, request: Request) -> str:
        return str(request.url_for("upload_local_library_content", asset_id=asset_id))

    async def download_url(self, asset_id: str, key: str, request: Request) -> str:
        return str(request.url_for("download_local_library_content", asset_id=asset_id))

    async def inspect(self, key: str) -> tuple[int, bytes] | None:
        path = self.path(key)
        if not path.is_file():
            return None

        def read() -> tuple[int, bytes]:
            with path.open("rb") as stream:
                return path.stat().st_size, stream.read(4)

        return await asyncio.to_thread(read)
