"""Local filesystem implementation of the library storage contract."""

import asyncio
import logging
import shutil
import tempfile
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import Request

from camera_path.services.library_storage import LibraryStorage


class LocalLibraryStorage(LibraryStorage):
    def __init__(self, directory: Path) -> None:
        self.directory = directory.expanduser().resolve()
        self.directory.mkdir(parents=True, exist_ok=True)

    def path(self, key: str) -> Path:
        # Keys are generated by the server, never derived from user filenames.
        if Path(key).name != key or key in {".", ".."}:
            raise ValueError("invalid library key")
        return self.directory / key

    async def upload_url(self, asset_id: str, key: str, request: Request) -> str:
        return str(request.url_for("upload_local_library_content", asset_id=asset_id))

    async def download_url(self, asset_id: str, key: str, request: Request) -> str:
        return str(request.url_for("download_local_library_content", asset_id=asset_id))

    async def inspect(self, key: str) -> tuple[int, bytes] | None:
        path = self.path(key)
        if not path.is_file():
            return None

        def read() -> tuple[int, bytes]:
            with path.open("rb") as stream:
                return path.stat().st_size, stream.read(4)

        return await asyncio.to_thread(read)

    @asynccontextmanager
    async def stage_delete(self, keys: list[str]) -> AsyncIterator[None]:
        # Keep recoverable bytes until the SQL transaction has committed.
        # Renames stay on the same filesystem and never copy a multi-GB PLY.
        staging = Path(tempfile.mkdtemp(prefix=".delete-", dir=self.directory))
        moved: list[tuple[Path, Path]] = []
        preserve_staging = False
        try:
            for key in keys:
                source = self.path(key)
                destination = staging / key
                try:
                    source.replace(destination)
                except FileNotFoundError:
                    continue
                moved.append((source, destination))
            yield
        except BaseException:
            try:
                for source, destination in reversed(moved):
                    destination.replace(source)
            except BaseException:
                preserve_staging = True
                raise
            raise
        finally:
            try:
                if not preserve_staging:
                    shutil.rmtree(staging)
            except OSError:
                # After commit these are unreferenced trash bytes, never live files.
                logging.getLogger(__name__).exception("Could not clean deletion trash: %s", staging)
