export const ANCHOR_ICON_Z_INDEX_MIN = 1_000;
export const ANCHOR_ICON_Z_INDEX_MAX = 1_999;

export const FLOATING_UI_Z_INDEX_MIN = 2_000;
export const FLOATING_UI_Z_INDEX_MAX = 2_999;

export const FLOATING_PANEL_Z_INDEX = FLOATING_UI_Z_INDEX_MIN;
export const CONTEXT_MENU_Z_INDEX = FLOATING_UI_Z_INDEX_MAX;

export const ANCHOR_ICON_Z_INDEX_RANGE: [number, number] = [
  ANCHOR_ICON_Z_INDEX_MAX,
  ANCHOR_ICON_Z_INDEX_MIN,
];
